version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=some_password
    volumes:
      - ./_postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"